//
// Created by Olcay Taner YILDIZ on 10.05.2023.
//

#ifndef UNIVERSALDEPENDENCYPARSER_COMMAND_H
#define UNIVERSALDEPENDENCYPARSER_COMMAND_H

enum class Command{
    RIGHTARC, LEFTARC, SHIFT, REDUCE
};
#endif //UNIVERSALDEPENDENCYPARSER_COMMAND_H
