//
// Created by Olcay Taner YILDIZ on 10.05.2023.
//

#ifndef UNIVERSALDEPENDENCYPARSER_TRANSITIONSYSTEM_H
#define UNIVERSALDEPENDENCYPARSER_TRANSITIONSYSTEM_H

enum class TransitionSystem{
    ARC_STANDARD, ARC_EAGER
};

#endif //UNIVERSALDEPENDENCYPARSER_TRANSITIONSYSTEM_H
